#ifndef ONNX_MLIR_NNAY_COMPILER_OPTIONS_H
#define ONNX_MLIR_NNAY_COMPILER_OPTIONS_H

#include "llvm/Support/CommandLine.h"

#define INSTRUMENTSTAGE_ENUM_NNAY , MX, NNAYHL

#define INSTRUMENTSTAGE_CL_ENUM_NNAY                                           \
  , clEnumVal(MX, "MX"), clEnumVal(NNAYHL, "NNAYHL")

#define PROFILEIR_CL_ENUM_NNAY                                                 \
  , clEnumVal(NNAYHL, "Profile operations in NNAYHLIR generated by "           \
                      "--EmitNNAYHLIR.")

#define OPTREPORT_ENUM_NNAY , NNAYUnsupportedOps

#define OPTREPORT_CL_ENUM_NNAY                                                 \
  , clEnumVal(NNAYUnsupportedOps,                                              \
        "Provide report on why ONNX ops did not run on NNAY.")

namespace onnx_mlir {
typedef enum {
  EmitNNAYHLIR,
} NNAYEmissionTargetType;

extern llvm::cl::OptionCategory OnnxMlirOptions;
extern llvm::cl::OptionCategory OnnxMlirCommonOptions;
extern llvm::cl::opt<onnx_mlir::NNAYEmissionTargetType> nnayEmissionTarget;
} // namespace onnx_mlir

#endif
