set(NNAY_ENABLED 1 BOOL PARENT_SCOPE)

set(NNAY_SRC_ROOT "${CMAKE_CURRENT_SOURCE_DIR}")
set(NNAY_BIN_ROOT "${CMAKE_CURRENT_BINARY_DIR}")

set(NNAY_LIBRARY_PATH ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
set(NNAY_RUNTIME_PATH ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
set(NNAY_INCLUDE_PATH ${CMAKE_INCLUDE_OUTPUT_DIRECTORY})

set(NNAY_ONNX_MLIR_SRC_ROOT ${ONNX_MLIR_SRC_ROOT})
set(NNAY_ONNX_MLIR_BIN_ROOT ${ONNX_MLIR_BIN_ROOT})

add_subdirectory(Compiler)
add_subdirectory(Dialect)
add_subdirectory(Conversion)
add_subdirectory(Pass)

add_onnx_mlir_library(OMNNAYAccel
  NNAYAccelerator.cpp

  EXCLUDE_FROM_OM_LIBS
  
  INCLUDE_DIRS PUBLIC
  ${ONNX_MLIR_SRC_ROOT}/include
  ${ONNX_MLIR_SRC_ROOT}
  ${NNAY_ONNX_MLIR_SRC_ROOT}
  ${NNAY_SRC_ROOT}
  ${NNAY_BIN_ROOT}
  ${NNAY_INCLUDE_PATH}

  LINK_LIBS PUBLIC
  onnx
  OMAccelerator
  OMNNAYCompilerUtils
  OMNNAYHLDialect
  OMMXDialect
  OMNNAYPasses
)
